### ISSUE TITLE
Installing both grunt-cli and grunt globally

### ISSUE THREAD

**Issue by wesleytodd** [gruntjs/grunt-cli#10]
I ran into an issue while trying to get grunt v0.4.0rc7 working globally.  I understand that best practice is to include grunt locally to a project, and normally do.  But in this particular situation it makes more sense to install it globally.

The steps I have taken so far are as follows:

```
sudo npm install -g grunt-cli
sudo npm install -g grunt@0.4.0rc7
```

I have a `Gruntfile.js` in my project root with a basic `test` task that just prints "Works!".  When I run `grunt test` it fails saying `Fatal error: Unable to find local grunt.`.  I took a look at `node/bin/grunt` and logged the variable `gruntpath` inside the exit callback and it is an empty string.  Also the exit code is 11, not 0.  But if I replace all the logic for loading the cli module like:

``` javascript
require(require.resolve("grunt")).cli();
```

Everything works fine.

So am I missing something?  Is this just a fancy way of enforcing best practices and making people include grunt locally to a project?

**Comment by juliusakula** [comment]
I came here from google for *grunt cli not finding gruntfile windows*, and eventually I ran into a short checklist.

1. npm install grunt to get it into node_modules, *at the project level*, (if only installed globally, something something No)
2. within grunt file loadNpm task for each grunt task
3. npm install grunt-contrib-* (each package involved with 2)
4. registerTask 'default' set to a chronological list of tasks to be done
5. Now the command 'grunt' works.

**Comment by shawnholt** [comment]
Wow - gulp npm install global vs. local is making this newbie bull his hair out!

**Comment by pravi** [comment]
In debian we want the globally installed grunt to be used to build all packaged node modules (mainly to browserify them and run their tests). But I guess, the core developers are not going to implement this feature. Can anyone subscribed to this issue help me? Did anyone get it working?

I tried @tbull 's PR #55 but I get this error when running grunt,

```
$ grunt
Loading "Gruntfile.js" tasks...ERROR
>> Error: Unable to read "package.json" file (Error code: MODULE_NOT_FOUND).
Warning: Task "default" not found. Use --force to continue.
```

**Comment by pravi** [comment]
[This patch](https://anonscm.debian.org/cgit/pkg-javascript/grunt.git/tree/debian/patches/remove-encoding-conversion.patch) fixes the above problem. But not sure why that code snippet is failing.

**Comment by matamouros** [comment]
Yes, seems there's a lot of confirmation bias on this years old thread. We have a single app which is deployed to our servers, and crickey we need to run `npm install` on every deploy, on every server, just for the grunt toolchain, because grunt has as a requirement that it can't be used globally because reasons. Especially loved the guy saying that grunt is awesome and the whole thread is moot, because he definitely understands how everyone in the world is using this - and also understands a lot about CICD apparently.

I'm just seriously frustrated at having lost quite a few hours on streamlining our deployment process here, only to come to the realisation that I will have to always have an `npm install` on the root of our app because of this short-sighted design decision.

If anything think about it in terms of dependencies "for app to run" and dependencies "for app to build". The former should indeed be on a packages.json file to be executed on every deploy, as app dependencies required for the app to run can be loosely considered as an integral part of it. However, the latter (where grunt is) is part of the toolchain that builds the app. I most certainly don't expect gcc and all the toolchain around it to ship as part of the freaking C++ app - they exist globally to build it, and then they're out of the way once that's done.
